# Generated by Django 3.2.9 on 2021-12-06 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Друг', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
