# Generated by Django 3.2.9 on 2021-12-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_friend_users_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_key', models.CharField(blank=True, max_length=110, null=True, verbose_name='Открытый ключ')),
                ('secret_key', models.CharField(blank=True, max_length=110, null=True, verbose_name='Секретный ключ')),
            ],
        ),
    ]
