# Generated by Django 3.2.9 on 2021-12-06 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='keys_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Юзер', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='keys',
            name='open_key',
            field=models.CharField(blank=True, default='0', max_length=110, null=True, verbose_name='Открытый ключ'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='secret_key',
            field=models.CharField(blank=True, default='0', max_length=110, null=True, verbose_name='Секретный ключ'),
        ),
    ]
