# Generated by Django 3.2.9 on 2021-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211206_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='open_key',
            field=models.CharField(blank=True, default='0', max_length=210, null=True, verbose_name='Открытый ключ'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='secret_key',
            field=models.CharField(blank=True, default='0', max_length=210, null=True, verbose_name='Секретный ключ'),
        ),
    ]
